"""`flybench submit results/x.json` — validate, branch, commit, open the pull request.

Uses the GitHub CLI (`gh`) so the user never touches git directly. If gh is missing
or not logged in, prints the three manual steps instead of failing silently.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
from pathlib import Path

UPSTREAM = "brandoncho369/flybench"


def _run(cmd: list[str], check: bool = True, capture: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=check, text=True, capture_output=capture)


def pr_body(report: dict, note: str) -> str:
    p = report["params"]
    rows = []
    for t in report["tasks"]:
        mark = "✅" if t["passed"] else f"{t['score']:.0%}"
        rows.append(f"| {t['task']} | {mark} |")
    tasks = "\n".join(rows)
    return f"""## Result submission

- **Label:** `{report['label']}`
- **Connectome:** {report['connectome']} ({report.get('connectome_meta', {}).get('source', '?')}, min synapses {report.get('connectome_meta', {}).get('min_synapses', '?')})
- **Model:** `{report.get('simulator', 'flybench.sim.LIFSimulator')}` · gain {p['gain']} · w_syn {p['w_syn_mv']} mV · dt {p['dt_ms']} ms
- **Seeds:** {report.get('seeds', 1)}
- **Scores:** core {report.get('core_score')} · hard {report.get('hard_score')}
- **What changed:** {note or '_(please fill in)_'}

| task | result |
|---|---|
{tasks}

- [x] Generated by `flybench run`, validated by `flybench validate`
- [ ] I did **not** tune any per-neuron parameter to pass a task

_Opened with `flybench submit`._
"""


def submit(path: Path, note: str = "", dry_run: bool = False) -> int:
    from rich.console import Console

    from .validate import validate_report

    console = Console()
    report = json.loads(path.read_text(encoding="utf-8"))
    errs = validate_report(report)
    if errs:
        console.print("[red]report is not valid:[/]")
        for e in errs:
            console.print("  " + e)
        return 1
    label = report["label"]
    slug = re.sub(r"[^a-z0-9]+", "-", label.lower()).strip("-")[:40] or "result"
    branch = f"submit/{slug}"
    title = f"Result: {label}"
    body = pr_body(report, note)

    if dry_run:
        console.print(f"[bold]would[/] create branch {branch}, commit {path}, and open PR {title!r} against {UPSTREAM}")
        console.print(body)
        return 0

    manual = f"""[yellow]Manual steps:[/]
  git checkout -b {branch}
  git add {path}
  git commit -m "{title}"
  git push -u origin {branch}
  then open a pull request against {UPSTREAM} and paste the PR template."""

    if shutil.which("gh") is None:
        console.print("[red]GitHub CLI (gh) not found.[/] Install from https://cli.github.com then run `gh auth login`.")
        console.print(manual); return 2
    if _run(["gh", "auth", "status"], check=False).returncode != 0:
        console.print("[red]gh is not logged in.[/] Run `gh auth login` first."); console.print(manual); return 2
    if _run(["git", "rev-parse", "--is-inside-work-tree"], check=False).returncode != 0:
        console.print("[red]not inside a git checkout of flybench.[/]"); console.print(manual); return 2

    try:
        _run(["git", "checkout", "-B", branch])
        _run(["git", "add", str(path)])
        if _run(["git", "diff", "--cached", "--quiet"], check=False).returncode == 0:
            console.print("[yellow]nothing to commit — is the result already committed?[/]")
        else:
            _run(["git", "commit", "-m", title])
        console.print(f"branch [bold]{branch}[/] ready; opening the pull request (gh may ask to fork the repo — say yes)…")
        r = subprocess.run(["gh", "pr", "create", "--repo", UPSTREAM, "--title", title, "--body", body, "--head", branch], text=True)
        if r.returncode != 0:
            console.print("[red]gh pr create failed.[/]"); console.print(manual); return r.returncode
    except subprocess.CalledProcessError as e:
        console.print(f"[red]{' '.join(e.cmd)} failed:[/] {e.stderr or ''}"); console.print(manual); return e.returncode
    console.print("[green]pull request opened.[/] CI will validate it; a maintainer re-runs it before it is marked verified.")
    return 0
